<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [cpp-threads] pthread_cancel and EH: let's try this again
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bcpp-threads%5D%20pthread_cancel%20and%20EH%3A%20let%27s%20try%20this%20again&In-Reply-To=%3C001501c5863e%2425ad0ec0%246501a8c0%40pdimov%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000324.html">
   <LINK REL="Next"  HREF="000327.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[cpp-threads] pthread_cancel and EH: let's try this again</H1>
    <B>Peter Dimov</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bcpp-threads%5D%20pthread_cancel%20and%20EH%3A%20let%27s%20try%20this%20again&In-Reply-To=%3C001501c5863e%2425ad0ec0%246501a8c0%40pdimov%3E"
       TITLE="[cpp-threads] pthread_cancel and EH: let's try this again">pdimov at mmltd.net
       </A><BR>
    <I>Mon Jul 11 17:29:48 UTC 2005</I>
    <P><UL>
        <LI>Previous message: <A HREF="000324.html">pthread_cancel and EH: let's try this again
</A></li>
        <LI>Next message: <A HREF="000327.html">[c++-pthreads] pthread_cancel and EH: let's try this again
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#325">[ date ]</a>
              <a href="thread.html#325">[ thread ]</a>
              <a href="subject.html#325">[ subject ]</a>
              <a href="author.html#325">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Some comments...

Jason Merrill wrote:

[...]

&gt;<i> In previous discussions, my favored solution was:
</I>&gt;<i> 1a) Cancellation is disabled during stack unwinding, to avoid trying
</I>&gt;<i> to throw out of a destructor.
</I>&gt;<i> 1b) Make cancellation a normal exception that can be caught and
</I>&gt;<i> discarded, but have the destructor for the exception re-assert
</I>&gt;<i> cancellation so that the process will begin again at the next
</I>&gt;<i> cancellation point.
</I>&gt;<i> Apparently this is also the Boost.Threads design.
</I>&gt;<i>
</I>&gt;<i> Then there's the Ada-equivalent model:
</I>&gt;<i> 2a) Cancellation is disabled during destructors and empty exception
</I>&gt;<i> specs.
</I>&gt;<i> 2b) Cancellation exceptions are not caught by (...).
</I>&gt;<i>
</I>&gt;<i> And the current status quo in GCC:
</I>&gt;<i> 3) #1, except that the destructor for the exception calls abort().
</I>&gt;<i> Additional inelegant possibilities for the destructor would be
</I>&gt;<i> killing just the thread, throwing a new exception, or doing nothing
</I>&gt;<i> (leaving the thread in a sort of zombie state).
</I>
1. Boost.Threads doesn't support cancellation. Very possibly never will.

2. The arguments in favor of ... not catching the cancellation exception can 
be summarized as:

2a. We can break perfectly valid catch(...)+rethrow cleanup code because 
it's inelegant.

2b. Some people that use catch(...) don't really want catch(...) semantics.

3. Non-empty exception specifications may terminate() on cancellation. 
(These are even less elegant than catch+rethrow, of course.)

This is also true in cases where the original code avoided terminate() by 
remapping exceptions:

void f() throw( MyException )
{
    try
    {
        g();
    }
    catch( MyException const &amp; )
    {
        throw;
    }
    catch( ... )
    {
        throw MyBadException();
    }
}

(Remapping via unexpected() will work, though, if the cancellation exception 
plays by the rules.)

4. Inter-language communication is usually done by translating the exception 
into a return code, squeezing that through an extern &quot;C&quot; interface, then 
optionally throwing at the other end. It isn't just catch and rethrow 
something else.

5. Disabling cancellation during empty exception specs is too coarse:

int f() throw()
{
    try
    {
        return lengthy_operation();
    }
    catch(...)
    {
        return EXCEPTION;
    }
}

I want cancellation to be active during lengthy_operation.

Summary:

I'm in favor of 1 minus the &quot;destructor reasserts&quot; part (it's not needed). 
I'm undecided on whether the cancellation request is (implicitly) cleared 
when the cancellation exception is thrown. There are good arguments in favor 
of either approach, and a reasonable compromise would be to not clear the 
cancellation request and provide a function for clearing it explicitly for 
the cases where this is desired.

Finally,

&gt;<i> People who want model #1 can use a different threading library, such as
</I>&gt;<i> Boost.Threads.
</I>
this is impossible on a number of levels. :-)


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000324.html">pthread_cancel and EH: let's try this again
</A></li>
	<LI>Next message: <A HREF="000327.html">[c++-pthreads] pthread_cancel and EH: let's try this again
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#325">[ date ]</a>
              <a href="thread.html#325">[ thread ]</a>
              <a href="subject.html#325">[ subject ]</a>
              <a href="author.html#325">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
