<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> pthread_cancel and EH: let's try this again
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20pthread_cancel%20and%20EH%3A%20let%27s%20try%20this%20again&In-Reply-To=%3C42DFBB38.791F2DDC%40web.de%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000486.html">
   <LINK REL="Next"  HREF="000490.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>pthread_cancel and EH: let's try this again</H1>
    <B>Alexander Terekhov</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20pthread_cancel%20and%20EH%3A%20let%27s%20try%20this%20again&In-Reply-To=%3C42DFBB38.791F2DDC%40web.de%3E"
       TITLE="pthread_cancel and EH: let's try this again">terekhov at web.de
       </A><BR>
    <I>Thu Jul 21 15:11:52 UTC 2005</I>
    <P><UL>
        <LI>Previous message: <A HREF="000486.html">[c++-pthreads]  Re: pthread_cancel and EH: let's try this again
</A></li>
        <LI>Next message: <A HREF="000490.html">pthread_cancel and EH: let's try this again
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#488">[ date ]</a>
              <a href="thread.html#488">[ thread ]</a>
              <a href="subject.html#488">[ subject ]</a>
              <a href="author.html#488">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>
Peter Dimov wrote:
[...]
&gt;<i> A simple solution is to adopt (1) and re-enable cancellation at the end of
</I>&gt;<i> the catch clause.
</I>&gt;<i> 
</I>&gt;<i> This solution is not without its merits and is actually a workable
</I>&gt;<i> approximation of the &quot;ideal&quot; model, but it has the following problem: the
</I>&gt;<i> proper value of the cancelability state after the exception is finalized may
</I>&gt;<i> be &quot;disabled&quot;. In the example below:
</I>&gt;<i> 
</I>&gt;<i> // #1
</I>&gt;<i> 
</I>&gt;<i> try
</I>&gt;<i> {
</I>&gt;<i>     f();
</I>&gt;<i> }
</I>&gt;<i> catch( ... )
</I>&gt;<i> {
</I>&gt;<i> }
</I>&gt;<i> 
</I>&gt;<i> // #2
</I>&gt;<i> 
</I>&gt;<i> the cancelability state at #2 ought to be the same as the cancelability
</I>&gt;<i> state at #1, provided that its only explicit manipulation is via a RAII
</I>&gt;<i> guards that always restore it to its previous value.
</I>
Let the user code do it. It's not that hard.

  // #1
  int cancelstate = std::thread_cancelstate();

  try
  {
      f();
  }
  catch( ... )
  {
    stick_cancel_and_ignore_exit(cancelstate);
  }

  // #2

with 

  void stick_cancel_and_ignore_exit(int cancelstate) throw() {
    try { 
      throw; 
    } 
    catch(const thread_termination_request &amp; request) { 
      if (cancelstate == PTHREAD_CANCEL_ENABLE)
        pthread_setcancelstate(cancelstate, &amp;cancelstate);
      if (request.exit_value_ptr() == PTHREAD_CANCELED)
        pthread_cancel(pthread_self());
      else ; // do whatever (if anything) so that it won't leak
    }
    catch(...) { }
  }

&gt;<i> Remembering the state at the cancellation point doesn't work; it may've 
</I>&gt;<i> been asynchronous. It may even have been disabled if the cancellation 
</I>&gt;<i> exception originated from an explicit user throw.
</I>
Such explicit user throw would violate the contract. It's sorta 
like insisting that some user's operator new(size_t, const 
std::nothrow_t &amp;) shall be able to exit with std::bad_alloc from 
explicit user throw and all should work just fine. But anyway,
see above.

&gt;<i> - the point of cancellation is to initiate stack unwinding, and when an
</I>&gt;<i> exception is active, stack unwinding is already under way;
</I>
That's not true under standard definition of stack unwinding.

&gt;<i> 
</I>&gt;<i> and
</I>&gt;<i> 
</I>&gt;<i> - given std::unfinished_exception(), the semantics of cancellation are also
</I>&gt;<i> implementable in user code or libraries 
</I>
You mean wrapping all cancellation points and async-cancel 
regions with

  disable_cancel_if_uncaught_exception_returns_true guard;

objects? Ugly.

regards,
alexander.


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000486.html">[c++-pthreads]  Re: pthread_cancel and EH: let's try this again
</A></li>
	<LI>Next message: <A HREF="000490.html">pthread_cancel and EH: let's try this again
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#488">[ date ]</a>
              <a href="thread.html#488">[ thread ]</a>
              <a href="subject.html#488">[ subject ]</a>
              <a href="author.html#488">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
