From daniel.christians at hp.com  Mon Dec  6 16:58:33 2004
From: daniel.christians at hp.com (Christians, Daniel)
Date: Mon, 6 Dec 2004 11:58:33 -0500
Subject: sigmask.so
Message-ID: <14013A008AB26E42B1FC18DECDCE2124046DDFCF@tayexc14.americas.cpqcorp.net>

Hi,

I am considering using QMTest for a test project but I am
having a problem with finding a library file after installing 
the rpm.   

[root]# qmtest
Traceback (most recent call last):
  File "/usr/bin/qmtest", line 135, in ?
    import qm.sigmask
ImportError: /usr/lib/python2.2/site-packages/qm/sigmask.so: cannot open
shared object file: No such file or directory [root at xc7n16 root]# rpm
-qa | grep qm qm-2.2-1 [root at xc7n16 root]# rpm --erase qm-2.2-1
[root at xc7n16 root]# ls -l /usr/lib/python2.2/site-packages/qm/sigmask.so
ls: /usr/lib/python2.2/site-packages/qm/sigmask.so: No such file or
directory [root at xc7n16 root]# ls -l /usr/lib/python2.2/site-packages/qm/
total 12
-rw-r--r--    1 root     root          281 Dec  6 11:38 config.pyc
drwxr-xr-x    3 root     root         4096 Dec  6 11:39 external
drwxr-xr-x    4 root     root         4096 Dec  6 11:39 test

We are using version 2.2.3 of python.

The systems this failed on are an Itanium and AMD opteron.

Without a 'sigmask.so' we would be able to run QMTest everwhere we
have Python installed, right?

Regards,

Dan Christians


From thomas_guyonnet at hotmail.com  Mon Dec 13 14:44:45 2004
From: thomas_guyonnet at hotmail.com (thomas guyonnet)
Date: Mon, 13 Dec 2004 14:44:45 +0000
Subject: qmtest and cygwin
Message-ID: <BAY102-F1010679E2FAAE02F74462689AB0@phx.gbl>

hello,
I'm a french developper (so sorry for my poor english) and  I try to use 
qmtest. I use cygwin in a windows NT OS and I have the pyton 2.4 version.
After installing qm-2.2.linux-i686.tar.gz et follow the instructions of the 
user's guide, I can't  execute anything. When I try 'qmtest run' or 'qmtest 
gui', an error message appear:
bash: /usr/bin/qmtest: /usr/bin/python2: bad interpreter: No such file or 
directory

can you help me?
thanks...

_________________________________________________________________
MSN Actions Solidaires : volontaire ? l'?tranger 
http://www.msn.fr/actionssolidaires/Default.asp?Ath=f



From mark at codesourcery.com  Mon Dec 13 15:30:31 2004
From: mark at codesourcery.com (Mark Mitchell)
Date: Mon, 13 Dec 2004 07:30:31 -0800
Subject: [qmtest] qmtest and cygwin
In-Reply-To: <BAY102-F1010679E2FAAE02F74462689AB0@phx.gbl>
References: <BAY102-F1010679E2FAAE02F74462689AB0@phx.gbl>
Message-ID: <41BDB597.40105@codesourcery.com>

thomas guyonnet wrote:
> hello,
> I'm a french developper (so sorry for my poor english) and  I try to use 
> qmtest. I use cygwin in a windows NT OS and I have the pyton 2.4 version.
> After installing qm-2.2.linux-i686.tar.gz et follow the instructions of 
> the user's guide, I can't  execute anything. When I try 'qmtest run' or 
> 'qmtest gui', an error message appear:
> bash: /usr/bin/qmtest: /usr/bin/python2: bad interpreter: No such file 
> or directory

QMTest doesn't support Cygwin directly.  It's best to use the native 
Windows version on Windows.  It certainly could be made to work with 
Cygwin, but nobody has done that.  The basic change would be to find the 
places that check the operating system in use to see if it is Windows, 
and use and change them to use a function that determines whether or not 
the system is Windows and not Cygwin.  Patches welcome!

-- 
Mark Mitchell
CodeSourcery, LLC
mark at codesourcery.com
(916) 791-8304


From seefeld at sympatico.ca  Mon Dec 13 22:33:55 2004
From: seefeld at sympatico.ca (Stefan Seefeld)
Date: Mon, 13 Dec 2004 17:33:55 -0500
Subject: [qmtest] qmtest and cygwin
In-Reply-To: <41BDB597.40105@codesourcery.com>
References: <BAY102-F1010679E2FAAE02F74462689AB0@phx.gbl> <41BDB597.40105@codesourcery.com>
Message-ID: <41BE18D3.4020000@sympatico.ca>

Mark Mitchell wrote:
> thomas guyonnet wrote:
> 
>> hello,
>> I'm a french developper (so sorry for my poor english) and  I try to 
>> use qmtest. I use cygwin in a windows NT OS and I have the pyton 2.4 
>> version.
>> After installing qm-2.2.linux-i686.tar.gz et follow the instructions 
>> of the user's guide, I can't  execute anything. When I try 'qmtest 
>> run' or 'qmtest gui', an error message appear:
>> bash: /usr/bin/qmtest: /usr/bin/python2: bad interpreter: No such file 
>> or directory
> 
> 
> QMTest doesn't support Cygwin directly.  It's best to use the native 
> Windows version on Windows.  It certainly could be made to work with 
> Cygwin, but nobody has done that.  The basic change would be to find the 
> places that check the operating system in use to see if it is Windows, 
> and use and change them to use a function that determines whether or not 
> the system is Windows and not Cygwin.  Patches welcome!


I remember having considered to support both win32 as well as cygwin when
working on the installation procedure. I believe the reason not to use
cygwin had been some problems with subprocess management on that platform
(i.e. some issues with the interaction between the OS and the cygwin runtime
library).
It may be worth trying with more recent versions of python/cygwin/windows.

Regards,
		Stefan


From mark at codesourcery.com  Mon Dec 13 22:53:55 2004
From: mark at codesourcery.com (Mark Mitchell)
Date: Mon, 13 Dec 2004 14:53:55 -0800
Subject: [qmtest] sigmask.so
In-Reply-To: <14013A008AB26E42B1FC18DECDCE2124046DDFCF@tayexc14.americas.cpqcorp.net>
References: <14013A008AB26E42B1FC18DECDCE2124046DDFCF@tayexc14.americas.cpqcorp.net>
Message-ID: <41BE1D83.5090103@codesourcery.com>

Christians, Daniel wrote:
> Hi,
> 
> I am considering using QMTest for a test project but I am
> having a problem with finding a library file after installing 
> the rpm.   

I'm a bit surprised; that file should be built when the RPM is 
installed, I think.  Stefan, can you clarify?

> The systems this failed on are an Itanium and AMD opteron.

> Without a 'sigmask.so' we would be able to run QMTest everwhere we
> have Python installed, right?

Yes.  But, assuming your operating system is GNU/Linux, or something 
else UNIX-like, you can probably get sigmask.so working on your systems 
too.  You can also, as a quick hack, comment amount the references to 
sigmask in executable.py and qmtest.py.  (Basically, just grep the 
sources for "sigmask").  If you do that, you'll get somewhat inferior 
functionality, in that signals in spawned threads will not work as well, 
but using ProcessTarget instead of ThreadTarget can work around that issue.

-- 
Mark Mitchell
CodeSourcery, LLC
mark at codesourcery.com
(916) 791-8304


From kenh at canada.com  Mon Dec 13 23:45:17 2004
From: kenh at canada.com (Ken Horovatin)
Date: Mon, 13 Dec 2004 15:45:17 -0800 (PST)
Subject: Python 2.4?
Message-ID: <20041213154517.7342.h012.c009.wm@mail.canada.com.criticalpath.net>

Has anyone looked at running QMTest on Python 2.4? 

I'm particularly interested if the changes to the subprocess module would open
the door to using the process target on Windows.


From mark at codesourcery.com  Tue Dec 14 00:11:19 2004
From: mark at codesourcery.com (Mark Mitchell)
Date: Mon, 13 Dec 2004 16:11:19 -0800
Subject: [qmtest] Python 2.4?
In-Reply-To: <20041213154517.7342.h012.c009.wm@mail.canada.com.criticalpath.net>
References: <20041213154517.7342.h012.c009.wm@mail.canada.com.criticalpath.net>
Message-ID: <41BE2FA7.6080306@codesourcery.com>

Ken Horovatin wrote:
> Has anyone looked at running QMTest on Python 2.4? 

I've not, but ...

> I'm particularly interested if the changes to the subprocess module would open
> the door to using the process target on Windows.

... that would be great.  However, I think that some of the things that 
executable.py presently does are probably too complex to be handled with 
the subprocess module.  I suspect, however, that executable.py could 
itself make available as abstractions enough to permit 
ProcessTarget.QMTestExecutable to contain no OS-dependent code.  In 
fact, I don't really see any reason that QMTestExecutable couldn't 
derive from RedirectedExecutable.  Do you have any interest in trying to 
put together a patch to do that?

-- 
Mark Mitchell
CodeSourcery, LLC
mark at codesourcery.com
(916) 791-8304


From seefeld at sympatico.ca  Tue Dec 14 02:04:25 2004
From: seefeld at sympatico.ca (Stefan Seefeld)
Date: Mon, 13 Dec 2004 21:04:25 -0500
Subject: [qmtest] sigmask.so
In-Reply-To: <14013A008AB26E42B1FC18DECDCE2124046DDFCF@tayexc14.americas.cpqcorp.net>
References: <14013A008AB26E42B1FC18DECDCE2124046DDFCF@tayexc14.americas.cpqcorp.net>
Message-ID: <41BE4A29.2090104@sympatico.ca>

Christians, Daniel wrote:
> Hi,
> 
> I am considering using QMTest for a test project but I am
> having a problem with finding a library file after installing 
> the rpm.   
> 
> [root]# qmtest
> Traceback (most recent call last):
>   File "/usr/bin/qmtest", line 135, in ?
>     import qm.sigmask
> ImportError: /usr/lib/python2.2/site-packages/qm/sigmask.so: cannot open
> shared object file: No such file or directory 

That is strange, as the qm-2.2-1.i386.rpm package does indeed contain sigmask.so:

bash-3.00$ rpm -qpil qm-2.2-1.i386.rpm | grep sigmask.so
/usr/lib/python2.2/site-packages/qm/sigmask.so


> [root at xc7n16 root]# rpm
> -qa | grep qm qm-2.2-1 [root at xc7n16 root]# rpm --erase qm-2.2-1
> [root at xc7n16 root]# ls -l /usr/lib/python2.2/site-packages/qm/sigmask.so
> ls: /usr/lib/python2.2/site-packages/qm/sigmask.so: No such file or
> directory [root at xc7n16 root]# ls -l /usr/lib/python2.2/site-packages/qm/
> total 12
> -rw-r--r--    1 root     root          281 Dec  6 11:38 config.pyc
> drwxr-xr-x    3 root     root         4096 Dec  6 11:39 external
> drwxr-xr-x    4 root     root         4096 Dec  6 11:39 test

right, after you erase the rpm these three items remain in the 'qm'
python package.

> We are using version 2.2.3 of python.
> 
> The systems this failed on are an Itanium and AMD opteron.

I can't comment on binary compatibility and rpm's behavior on these
machines. Can these machines run ELF 32-bit binaries compiled for
i386 ?
The fact that you managed to install the rpm seems to indicate
that they can. But may be there's some problem making rpm not
installing the extension file.

Alternatively, can you try to compile qmtest from the source package
on the target machine ?

Regards,
		Stefan



From mats.d.wichmann at intel.com  Tue Dec 14 02:23:03 2004
From: mats.d.wichmann at intel.com (Wichmann, Mats D)
Date: Mon, 13 Dec 2004 18:23:03 -0800
Subject: [qmtest] sigmask.so
Message-ID: <A06801158AE07847B27A52C1A074BC1D06CC0CE4@fmsmsx404.amr.corp.intel.com>


>> I am considering using QMTest for a test project but I am
>> having a problem with finding a library file after installing 
>> the rpm.   
>> 
>> [root]# qmtest
>> Traceback (most recent call last):
>>   File "/usr/bin/qmtest", line 135, in ?
>>     import qm.sigmask
>> ImportError: /usr/lib/python2.2/site-packages/qm/sigmask.so: 
>cannot open
>> shared object file: No such file or directory 
>
>That is strange, as the qm-2.2-1.i386.rpm package does indeed 
>contain sigmask.so:
>
>bash-3.00$ rpm -qpil qm-2.2-1.i386.rpm | grep sigmask.so
>/usr/lib/python2.2/site-packages/qm/sigmask.so

It's really unfortunate for the hope of building portable rpm
packages that python likes to embed the version in the path.
I understand why this is so, but it's still a pain for 'binary'
(as in not-source) packages.

At least for x86_64, the path is wrong, and you can't use this
package unless you intend to also use an x86 (not x86_64) Python:
x86_64 installs to /usr/lib64/pythonX.Y 

I'm also somewhat surprised that x86_64 distributions come with
Python 2.2.3, I thought most of the "production" distros were
using Python 2.3.x

Basically it looks like "build from source" is going to be the path...

>> [root at xc7n16 root]# rpm -qa | grep qm qm-2.2-1 

This command, if it was captured verbatim and is not
just a transcripton error, is not what you wanted...



From thomas_guyonnet at hotmail.com  Tue Dec 14 09:12:22 2004
From: thomas_guyonnet at hotmail.com (thomas guyonnet)
Date: Tue, 14 Dec 2004 09:12:22 +0000
Subject: problem with qmtest tutorial
Message-ID: <BAY102-F31B1E96D3950607D1BB9DC89AC0@phx.gbl>

hello,
I try to use QMTest on window and it seems to have some bugs with the 
example:
- when I try to examin the test clicking on the exec1 label, a new page 
appear with this dialog:

          __________________________________________________________________

You Have Found a Bug in QMTest!
This page indicates that QMTest has encountered an internal error.
You can return to the main page.

Exception type: exceptions.UnboundLocalError

Exception value: local variable 'item' referenced before assignment

Stack trace:
  File "C:\Python24\lib\site-packages\qm\web.py", line 476, in 
__HandleScriptRequest
    script_output = self.server.ProcessScript(request)

  File "C:\Python24\lib\site-packages\qm\web.py", line 821, in ProcessScript
    return self.__scripts[request.GetUrl()](request)

  File "C:\Python24\lib\site-packages\qm\test\web\web.py", line 2066, in 
HandleShowItem
    return ShowItemPage(self, item, edit, create, type)(request)

           ________________________________________________________________

- I also want to try to modify a test and in the edit menu, I haven't found 
: "Edit Test".

Do you know why these bugs occured and how I can fix them?

thanks.

_________________________________________________________________
MSN Messenger : dialoguez en temps r?el avec vos amis ! 
http://g.msn.fr/FR1001/866



From mark at codesourcery.com  Wed Dec 15 17:58:40 2004
From: mark at codesourcery.com (Mark Mitchell)
Date: Wed, 15 Dec 2004 09:58:40 -0800
Subject: [qmtest] problem with qmtest tutorial
In-Reply-To: <BAY102-F31B1E96D3950607D1BB9DC89AC0@phx.gbl>
References: <BAY102-F31B1E96D3950607D1BB9DC89AC0@phx.gbl>
Message-ID: <41C07B50.7040804@codesourcery.com>

thomas guyonnet wrote:
> hello,
> I try to use QMTest on window and it seems to have some bugs with the 
> example:
> - when I try to examin the test clicking on the exec1 label, a new page 
> appear with this dialog:

That's very odd; I've never seen that before.  It's possible that it's a 
side effect of using Python 2.4, but I'm not sure why that would be. 
I'm afraid that you'll have to debug the code.

-- 
Mark Mitchell
CodeSourcery, LLC
mark at codesourcery.com
(916) 791-8304


From seefeld at sympatico.ca  Thu Dec 16 01:39:41 2004
From: seefeld at sympatico.ca (Stefan Seefeld)
Date: Wed, 15 Dec 2004 20:39:41 -0500
Subject: [qmtest] problem with qmtest tutorial
In-Reply-To: <41C07B50.7040804@codesourcery.com>
References: <BAY102-F31B1E96D3950607D1BB9DC89AC0@phx.gbl> <41C07B50.7040804@codesourcery.com>
Message-ID: <41C0E75D.3030001@sympatico.ca>

Mark Mitchell wrote:
 > thomas guyonnet wrote:
 >
 >> hello,
 >> I try to use QMTest on window and it seems to have some bugs with the
 >> example:
 >> - when I try to examin the test clicking on the exec1 label, a new
 >> page appear with this dialog:
 >
 >
 > That's very odd; I've never seen that before.  It's possible that it's a
 > side effect of using Python 2.4, but I'm not sure why that would be. I'm
 > afraid that you'll have to debug the code.

I'v debugged that a bit, and I can confirm the bug. It is caused by the
wrong use of the binary 'is' operator to compare strings in the 'web.py'
module, which accidentally worked on python prior to version 2.4.
The control flow falls through the comparison around line 2057 where
it is assumed that the 'type' variable is either 'test' or 'resource'.
As both tests fail, the 'item' variable remains unbound, and thus the
exception is thrown.
Solution: replace the use of 'is' by '==' to compare strings.

Regards,
		Stefan


From mark at codesourcery.com  Thu Dec 16 01:52:56 2004
From: mark at codesourcery.com (Mark Mitchell)
Date: Wed, 15 Dec 2004 17:52:56 -0800
Subject: [qmtest] problem with qmtest tutorial
In-Reply-To: <41C0E75D.3030001@sympatico.ca>
References: <BAY102-F31B1E96D3950607D1BB9DC89AC0@phx.gbl> <41C07B50.7040804@codesourcery.com> <41C0E75D.3030001@sympatico.ca>
Message-ID: <41C0EA78.2010604@codesourcery.com>

Stefan Seefeld wrote:
> Mark Mitchell wrote:
>  > thomas guyonnet wrote:
>  >
>  >> hello,
>  >> I try to use QMTest on window and it seems to have some bugs with the
>  >> example:
>  >> - when I try to examin the test clicking on the exec1 label, a new
>  >> page appear with this dialog:
>  >
>  >
>  > That's very odd; I've never seen that before.  It's possible that it's a
>  > side effect of using Python 2.4, but I'm not sure why that would be. I'm
>  > afraid that you'll have to debug the code.

> Solution: replace the use of 'is' by '==' to compare strings.

Oh, dear -- I wonder how many places we made that mistake.  I think it 
was semi-intentional; some functional languages guarantee equal strings 
will be "eq", not just "eql".  Got a patch?

-- 
Mark Mitchell
CodeSourcery, LLC
mark at codesourcery.com
(916) 791-8304


From njs at pobox.com  Thu Dec 16 07:29:10 2004
From: njs at pobox.com (Nathaniel Smith)
Date: Wed, 15 Dec 2004 23:29:10 -0800
Subject: [qmtest] problem with qmtest tutorial
In-Reply-To: <41C0EA78.2010604@codesourcery.com>
References: <BAY102-F31B1E96D3950607D1BB9DC89AC0@phx.gbl> <41C07B50.7040804@codesourcery.com> <41C0E75D.3030001@sympatico.ca> <41C0EA78.2010604@codesourcery.com>
Message-ID: <20041216072910.GB18308@frances.vorpus.org>

On Wed, Dec 15, 2004 at 05:52:56PM -0800, Mark Mitchell wrote:
> Oh, dear -- I wonder how many places we made that mistake.  I think it 
> was semi-intentional; some functional languages guarantee equal strings 
> will be "eq", not just "eql".  Got a patch?

It probably has something to do with, everywhere else in the code we
use the object Database.RESOURCE (which happens to == "resource") as
our tag for resources, and _do_ intentionally use "is" comparisons.
Which are correct, albeit kinda premature optimizational.

-- Nathaniel

-- 
.i dei jitfa fanmo xatra


From seefeld at sympatico.ca  Thu Dec 16 22:00:33 2004
From: seefeld at sympatico.ca (Stefan Seefeld)
Date: Thu, 16 Dec 2004 17:00:33 -0500
Subject: [qmtest] problem with qmtest tutorial
In-Reply-To: <41C0EA78.2010604@codesourcery.com>
References: <BAY102-F31B1E96D3950607D1BB9DC89AC0@phx.gbl> <41C07B50.7040804@codesourcery.com> <41C0E75D.3030001@sympatico.ca> <41C0EA78.2010604@codesourcery.com>
Message-ID: <41C20581.8000507@sympatico.ca>

Mark Mitchell wrote:

 > Oh, dear -- I wonder how many places we made that mistake.  I think it
 > was semi-intentional; some functional languages guarantee equal strings
 > will be "eq", not just "eql".  Got a patch?

yes, it's checked in. 'qmtest gui' seems to work fine with python 2.4 now
(tested before and after the change on my FC3 box).

Regards,
		Stefan




From seefeld at sympatico.ca  Thu Dec 16 22:18:41 2004
From: seefeld at sympatico.ca (Stefan Seefeld)
Date: Thu, 16 Dec 2004 17:18:41 -0500
Subject: [qmtest] problem with qmtest tutorial
In-Reply-To: <41C20581.8000507@sympatico.ca>
References: <BAY102-F31B1E96D3950607D1BB9DC89AC0@phx.gbl> <41C07B50.7040804@codesourcery.com> <41C0E75D.3030001@sympatico.ca> <41C0EA78.2010604@codesourcery.com> <41C20581.8000507@sympatico.ca>
Message-ID: <41C209C1.3090408@sympatico.ca>

Stefan Seefeld wrote:

> yes, it's checked in. 'qmtest gui' seems to work fine with python 2.4 now
> (tested before and after the change on my FC3 box).

...and here, for the record, is the patch.

Regards,
		Stefan



-------------- next part --------------
An embedded and charset-unspecified text was scrubbed...
Name: patch
URL: <http://sourcerytools.com/pipermail/qmtest/attachments/20041216/571ac0c6/attachment.ksh>

