<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [c++-pthreads] Re: thread-safety definition
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20Re%3A%20thread-safety%20definition&In-Reply-To=%3C40006C6D.5090707%40bogo.xs4all.nl%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000180.html">
   <LINK REL="Next"  HREF="000194.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[c++-pthreads] Re: thread-safety definition</H1>
    <B>Wil Evers</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20Re%3A%20thread-safety%20definition&In-Reply-To=%3C40006C6D.5090707%40bogo.xs4all.nl%3E"
       TITLE="[c++-pthreads] Re: thread-safety definition">wil at bogo.xs4all.nl
       </A><BR>
    <I>Sat Jan 10 21:19:41 UTC 2004</I>
    <P><UL>
        <LI>Previous message: <A HREF="000180.html">[c++-pthreads] Re: thread-safety definition
</A></li>
        <LI>Next message: <A HREF="000194.html">[c++-pthreads] Re: thread-safety definition
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#193">[ date ]</a>
              <a href="thread.html#193">[ thread ]</a>
              <a href="subject.html#193">[ subject ]</a>
              <a href="author.html#193">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Richard Henderson wrote:

&gt;<i> On Fri, Jan 09, 2004 at 07:01:31AM +0100, Wil Evers wrote:
</I>&gt;<i> 
</I>&gt;&gt;<i>A second exception escaping from a destructor called while unwinding
</I>&gt;&gt;<i>the stack because of some earlier exception will result in program
</I>&gt;&gt;<i>termination.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>If catching (and not rethrowing) this second exception breaks the 
</I>&gt;&gt;<i>cancellation machinery, then it is the cancellation machinery - and not 
</I>&gt;&gt;<i>the program in question - that is broken.  In other words: we need a way 
</I>&gt;&gt;<i>to prevent this scenario.
</I>&gt;<i>  
</I>&gt;<i> It would be trivial to adjust the c++ runtime to disable cancelation
</I>&gt;<i> while exceptions are in flight.  That avoids that scenario entirely.
</I>
It obviously does.  But does that imply we don't need 
'catch-and-dont-rethrow' blocks in destructors anymore?  Please consider 
this example:

remote_resource_holder::~remote_resource_holder()
{
   remote_resource-&gt;release();
}

Disabling cancellation while exceptions are 'in flight' means we can't 
run into a double fault because of a cancellation request detected in 
remote_resource-&gt;release() while unwinding on behalf of some previously 
raised exception.  However, we may also be unwinding on behalf of some 
previously detected cancellation request, and it that case, a networking 
exception thrown from within remote_resource-&gt;release() *will* cause the 
program to terminate.

Please note that this problem is not caused by the use of exceptions for 
handling cancellation; any other previously raised exception could lead 
   to the same disaster scenario - which is why thinking about 
cancellation as some special kind of exception is unsufficient.

Instead, this example serves to show how dangerous it is to let 
exceptions escape from destructors.  Especially when we don't now which 
exceptions may be thrown from remote_resource-&gt;release(), about the only 
reasonable implementation of this destructor is:

remote_resource_holder::~remote_resource_holder()
{
   try {
     remote_resource-&gt;release();
   } catch (...) {
     // We may try to log what happened,
     // but can't let the exception escape!
   }
}

I've noticed that some people on this list object to this design, but so 
far, I haven't seen an alternative.  In other words, I think we should 
be prepared for threads that discard cancellation exceptions - which is 
why Nathan's 'sticky cancellation' makes sense to me.

- Wil


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000180.html">[c++-pthreads] Re: thread-safety definition
</A></li>
	<LI>Next message: <A HREF="000194.html">[c++-pthreads] Re: thread-safety definition
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#193">[ date ]</a>
              <a href="thread.html#193">[ thread ]</a>
              <a href="subject.html#193">[ subject ]</a>
              <a href="author.html#193">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
