<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [c++-pthreads] Restating the Jason model
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20Restating%20the%20Jason%20model&In-Reply-To=%3C4007FFCA.3000807%40bogo.xs4all.nl%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000276.html">
   <LINK REL="Next"  HREF="000278.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[c++-pthreads] Restating the Jason model</H1>
    <B>Wil Evers</B> 
    <A HREF="mailto:c%2B%2B-pthreads%40codesourcery.com?Subject=Re%3A%20%5Bc%2B%2B-pthreads%5D%20Restating%20the%20Jason%20model&In-Reply-To=%3C4007FFCA.3000807%40bogo.xs4all.nl%3E"
       TITLE="[c++-pthreads] Restating the Jason model">wil at bogo.xs4all.nl
       </A><BR>
    <I>Fri Jan 16 15:14:18 UTC 2004</I>
    <P><UL>
        <LI>Previous message: <A HREF="000276.html">[c++-pthreads] Restating the Jason model
</A></li>
        <LI>Next message: <A HREF="000278.html">[c++-pthreads] Restating the Jason model
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#277">[ date ]</a>
              <a href="thread.html#277">[ thread ]</a>
              <a href="subject.html#277">[ subject ]</a>
              <a href="author.html#277">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Jason Merrill wrote:

&gt;<i> On Tue, 13 Jan 2004 21:19:15 +0100, Wil Evers &lt;<A HREF="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">wil at bogo.xs4all.nl</A>&gt; wrote:
</I> &gt;
&gt;&gt;<i>It is true that an exception escaping from a destructor will not trigger
</I>&gt;&gt;<i>immediate program termination when the program/thread in question is not
</I>&gt;&gt;<i>unwinding; however, that doesn't mean there's nothing to worry about. The
</I>&gt;&gt;<i>most likely symptom is a resource leak; in a multi-threaded environment,
</I>&gt;&gt;<i>that could mean a deadlock.
</I>&gt;<i>  
</I>&gt;<i> True, throwing out of a destructor is more likely to cause trouble than
</I>&gt;<i> throwing from other places; a destructor like
</I>&gt;<i> 
</I>&gt;<i>   Guard::~Guard()
</I>&gt;<i>   {
</I>&gt;<i>     write (0, &quot;releasing&quot;, sizeof (&quot;releasing&quot;);
</I>&gt;<i>     release (resource);
</I>&gt;<i>   }
</I>&gt;<i> 
</I>&gt;<i> will fail to actually release the resource if a cancel is delivered during
</I>&gt;<i> the call to write().  It's certainly possible to restructure code to avoid
</I>&gt;<i> this problem, but I can see this being a source of hard-to-debug problems.
</I>
The situation is actually a bit more complicated: many container 
implementations, including the ones in the C++ standard library, assume 
that the destructors of their elements do not throw.   Most likely, an 
exception escaping from one element's destructor will cause the 
remaining elements to be abandoned (and not destroyed at all).

&gt;<i> This is a somewhat persuasive case for disabling cancel during all
</I>&gt;<i> destructors, but I'm not sure it outweighs the overhead involved.  In the
</I>&gt;<i> model I proposed, only the EH runtime needs to know about cancellation.
</I>
As I tried to say before, my main objection to your model is that, 
depending on the thread's dynamic context, destructors will behave 
differently when hitting a cancellation point.  Sometimes, your model 
will protect us from cancellation exceptions, but at other times it 
won't, and I fear the confusion that might result from this.

I agree that the overhead of disabling cancellation in all destructors 
could become a problem.  IMO, if we have sticky cancellation, the EH 
runtime doesn't need to be disable cancellation either.

Most destructors only deal with releasing memory anyway, and don't need 
to call any throwing functions.  Some destructors do more complicated 
things, involving calls to functions that *do* throw exceptions.  These 
destructors must take extra precautions and are harder to implement, but 
this has always been the case - ever since exceptions were added to C++.

The thing that changes because of cancellation is that some functions 
that didn't throw before will now be licensed to do so.  It seems to me 
that most of the participants on this mailing list accept that this will 
require changes to existing code.  That could include adding a try/catch 
block to destructor code.

- Wil


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000276.html">[c++-pthreads] Restating the Jason model
</A></li>
	<LI>Next message: <A HREF="000278.html">[c++-pthreads] Restating the Jason model
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#277">[ date ]</a>
              <a href="thread.html#277">[ thread ]</a>
              <a href="subject.html#277">[ subject ]</a>
              <a href="author.html#277">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/c++-pthreads">More information about the c++-pthreads
mailing list</a><br>
</body></html>
