<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> BUG? error retrieving argument of user-defined exception
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:qmtest%40codesourcery.com?Subject=Re%3A%20BUG%3F%20error%20retrieving%20argument%20of%20user-defined%20exception&In-Reply-To=%3C3FFD9415.7000803%40nextone.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000687.html">
   <LINK REL="Next"  HREF="000676.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>BUG? error retrieving argument of user-defined exception</H1>
    <B>Scott Lowrey</B> 
    <A HREF="mailto:qmtest%40codesourcery.com?Subject=Re%3A%20BUG%3F%20error%20retrieving%20argument%20of%20user-defined%20exception&In-Reply-To=%3C3FFD9415.7000803%40nextone.com%3E"
       TITLE="BUG? error retrieving argument of user-defined exception">slowrey at nextone.com
       </A><BR>
    <I>Thu Jan  8 17:32:05 UTC 2004</I>
    <P><UL>
        <LI>Previous message: <A HREF="000687.html">[qmtest] BUG? create-tdb overwrites existing database
</A></li>
        <LI>Next message: <A HREF="000676.html">[qmtest] BUG? error retrieving argument of user-defined	exception
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#671">[ date ]</a>
              <a href="thread.html#671">[ thread ]</a>
              <a href="subject.html#671">[ subject ]</a>
              <a href="author.html#671">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>(Sorry if this is an inappropriate format but I want people to be able 
to just plug the test into their database and run it.)

The following exception test - using a builtin exception - works fine:

&lt;?xml version=&quot;1.0&quot;?&gt;
&lt;extension class=&quot;python.ExceptionTest&quot; kind=&quot;test&quot;&gt;
  &lt;argument name=&quot;exception_class&quot;&gt;
    &lt;text&gt;AssertionError&lt;/text&gt;
  &lt;/argument&gt;
  &lt;argument name=&quot;exception_argument&quot;&gt;
    &lt;text&gt;'this is the arg'&lt;/text&gt;
  &lt;/argument&gt;
  &lt;argument name=&quot;source&quot;&gt;
    &lt;text&gt;raise AssertionError('this is the arg')
&lt;/text&gt;
  &lt;/argument&gt;
  &lt;argument name=&quot;prerequisites&quot;&gt;
    &lt;set/&gt;
  &lt;/argument&gt;
  &lt;argument name=&quot;target_group&quot;&gt;
    &lt;text&gt;.*&lt;/text&gt;
  &lt;/argument&gt;
  &lt;argument name=&quot;resources&quot;&gt;
    &lt;set/&gt;
  &lt;/argument&gt;
&lt;/extension&gt;

This one - using a user-defined exception - fails to find the exception 
value:

&lt;?xml version=&quot;1.0&quot;?&gt;
&lt;extension class=&quot;python.ExceptionTest&quot; kind=&quot;test&quot;&gt;
  &lt;argument name=&quot;exception_class&quot;&gt;
    &lt;text&gt;MyExc&lt;/text&gt;
  &lt;/argument&gt;
  &lt;argument name=&quot;exception_argument&quot;&gt;
    &lt;text&gt;'this is the arg'&lt;/text&gt;
  &lt;/argument&gt;
  &lt;argument name=&quot;source&quot;&gt;
    &lt;text&gt;class MyExc(Exception):
    def __init__(self, value):
        self.value = value
    def __str__(self):
        return repr(self.value)

raise MyExc('this is the arg')
&lt;/text&gt;
  &lt;/argument&gt;
  &lt;argument name=&quot;prerequisites&quot;&gt;
    &lt;set/&gt;
  &lt;/argument&gt;
  &lt;argument name=&quot;target_group&quot;&gt;
    &lt;text&gt;.*&lt;/text&gt;
  &lt;/argument&gt;
  &lt;argument name=&quot;resources&quot;&gt;
    &lt;set/&gt;
  &lt;/argument&gt;
&lt;/extension&gt;

The error from QMTest is:

[<A HREF="http://sourcerytools.com/cgi-bin/mailman/listinfo/qmtest">slowrey at moondog</A> tmp]$ qmtest run myexc.exc1
--- TEST RESULTS 
-------------------------------------------------------------

  myexc.exc1                                    : ERROR
    An exception occurred.

    qmtest.exception:
      exceptions.AttributeError: MyExc instance has no attribute 'args'

    qmtest.target:
      local

    qmtest.traceback:

        File &quot;/opt/test/lib/qm/test/target.py&quot;, line 215, in RunTest
          descriptor.Run(context, result)

        File &quot;/opt/test/lib/qm/test/database.py&quot;, line 246, in Run
          self._Execute(context, result, &quot;Run&quot;)

        File &quot;/opt/test/lib/qm/test/database.py&quot;, line 168, in _Execute
          eval(&quot;item.%s(context, result)&quot; % method)

        File &quot;&quot;, line 0, in ?

        File &quot;/opt/test/lib/qm/test/classes/python.py&quot;, line 164, in Run
          self.CheckArgument(exc_info, result)

        File &quot;/opt/test/lib/qm/test/classes/python.py&quot;, line 245, in 
CheckArgument
          argument = exc_info[1].args



-- 
*Scott Lowrey*
NexTone Communications
Germantown, Maryland

/(240)912-1369/
www.nextone.com &lt;<A HREF="http://www.nextone.com">http://www.nextone.com</A>&gt;

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000687.html">[qmtest] BUG? create-tdb overwrites existing database
</A></li>
	<LI>Next message: <A HREF="000676.html">[qmtest] BUG? error retrieving argument of user-defined	exception
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#671">[ date ]</a>
              <a href="thread.html#671">[ thread ]</a>
              <a href="subject.html#671">[ subject ]</a>
              <a href="author.html#671">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/qmtest">More information about the qmtest
mailing list</a><br>
</body></html>
