<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> Test Completion With Running Processes
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:qmtest%40codesourcery.com?Subject=Re%3A%20Test%20Completion%20With%20Running%20Processes&In-Reply-To=%3C40155064.9000705%40nextone.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000723.html">
   
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>Test Completion With Running Processes</H1>
    <B>Scott Lowrey</B> 
    <A HREF="mailto:qmtest%40codesourcery.com?Subject=Re%3A%20Test%20Completion%20With%20Running%20Processes&In-Reply-To=%3C40155064.9000705%40nextone.com%3E"
       TITLE="Test Completion With Running Processes">slowrey at nextone.com
       </A><BR>
    <I>Mon Jan 26 17:37:40 UTC 2004</I>
    <P><UL>
        <LI>Previous message: <A HREF="000723.html">[qmtest] QMtest Suites
</A></li>
        
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#721">[ date ]</a>
              <a href="thread.html#721">[ thread ]</a>
              <a href="subject.html#721">[ subject ]</a>
              <a href="author.html#721">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>I've noticed a discrepancy in the behavior between running tests on the 
command line and running them via the GUI.

Scenario:

Test code spawns several subprocesses.  Exception occurs while executing 
test code.  Bug in the test class (mine) leaves one process outstanding.

Result:

If this test is run via the command line ('qmtest run'), the exception 
is properly noted and the test ends with an ERROR result.  The 
outstanding process remains as an orphan.

If this test is run via the GUI, the browser loops waiting for the test 
to end.

Obviously, QMTest is waiting for all processes associated with it to end 
before declaring the test complete.  That is a Good Thing, I think.  But 
why does the command-line test come back as soon as the exception 
occurs, in spite of the outstanding process?

-- 
*Scott Lowrey*
NexTone Communications
Germantown, Maryland

/(240)912-1369/
www.nextone.com &lt;<A HREF="http://www.nextone.com">http://www.nextone.com</A>&gt;
-------------- next part --------------
An HTML attachment was scrubbed...
URL: &lt;<A HREF="http://sourcerytools.com/pipermail/qmtest/attachments/20040126/9d8e157d/attachment.html">http://sourcerytools.com/pipermail/qmtest/attachments/20040126/9d8e157d/attachment.html</A>&gt;
</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000723.html">[qmtest] QMtest Suites
</A></li>
	
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#721">[ date ]</a>
              <a href="thread.html#721">[ thread ]</a>
              <a href="subject.html#721">[ subject ]</a>
              <a href="author.html#721">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/qmtest">More information about the qmtest
mailing list</a><br>
</body></html>
